service: pull-news-from-google

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  httpApi:
    cors: true
  environment:
    NODE_OPTIONS: '--enable-source-maps'
    DATABASE_URL: ${env.DATABASE_URL}
    PUPPETEER_SKIP_DOWNLOAD: true


package:
  individually: true

  patterns:
    - prisma/**                     # include your source schema (optional but nice)
    - node_modules/.prisma/**       # include generated client assets
    - node_modules/@prisma/**       # include engines

build:
  esbuild:
    # Path to the esbuild config file relative to the `serverless.yml` file
    configFile: ./esbuild.config.js
    target: node20
    platform: node
#    exclude:
#      - 'jsdom'
#      - 'canvas'
#    external:
#      - 'jsdom'
#      - 'canvas'
#      - '@postlight/parser'

functions:
  fetchNews:
    handler: src/handler.fetchNews
    events:
      - httpApi:
          path: /fetch-news
          method: POST
      - httpApi:
          path: /fetch-news
          method: OPTIONS
          handler: handler.handleOptions
