import { chapterGenerateRoute, ChapterGenerateResponse } from '@/app/api/industry-tariff-reports/chapters/[chapterSlug]/chapter-generate-handler';
import { getTariffUpdatesForIndustryAndSaveToFile } from '@/scripts/industry-tariff-reports/03-industry-tariffs';
import { getTodayDateAsMonthDDYYYYFormat } from '@/util/get-date';
import { withErrorHandlingV2 } from '@dodao/web-core/api/helpers/middlewares/withErrorHandling';

interface GenerateTariffUpdatesBody {
  date?: string;
  countryName?: string;
}

// Generates the `tariffUpdates` section. In SYNCHRONOUS mode the admin UI calls
// this once per country (`countryName` set) after `init-tariff-updates` returns
// the country list — chunking keeps each request under the origin timeout. In
// BACKGROUND mode (USE_LAMBDA_FOR_TARIFF_LLM_RESPONSE=true) the whole section is
// generated by a single background task kicked off from `init-tariff-updates`,
// so this per-country route isn't used.
export const POST = withErrorHandlingV2<ChapterGenerateResponse>(
  chapterGenerateRoute('tariffUpdates', async (slug, body) => {
    const { date, countryName } = (body as GenerateTariffUpdatesBody) ?? {};
    await getTariffUpdatesForIndustryAndSaveToFile(slug, date ?? getTodayDateAsMonthDDYYYYFormat(), countryName);
  })
);
