// Seeds the tariff_chapter_reports table from S3.
//
// For each (canonical industry → primary HTS chapter) pair below, fetches the
// industry's existing JSON sections from S3 and emits an INSERT statement that:
//  - resolves chapter_id via subquery on tariff_chapters (number)
//  - sets `slug` to the chapter's URL slug ({number}-{slug})
//  - sets `old_url` to the canonical industryId; the route handler matches
//    incoming `/industry-tariff-report/<industryId>/...` URLs against this.
//  - sets the five JSON section columns from the canonical industry's S3 data.
//
// Output: prisma/seeds/tariff-chapter-reports.sql (apply with psql).
//
// Run with: yarn tsx src/scripts/industry-tariff-reports/seed-tariff-chapter-reports.ts
import 'dotenv/config';
import { writeFile, mkdir } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { randomUUID } from 'node:crypto';
import {
  readReportCoverFromFile,
  readTariffUpdatesFromFile,
  readUnderstandIndustryJsonFromFile,
  readIndustryHeadingsFromFile,
  readFinalConclusionFromFile,
} from '@/scripts/industry-tariff-reports/tariff-report-read-write';
import { chapterUrlSlug, HTS_CHAPTERS, TariffIndustryId } from '@/scripts/industry-tariff-reports/tariff-industries';

interface ChapterSeed {
  // HTS chapter the row represents.
  chapterNumber: number;
  // Canonical industry whose S3 data populates the JSON columns AND whose
  // industryId is stored in old_url for legacy URL routing.
  industry: TariffIndustryId;
}

// Most-broadly-relevant HTS chapter per industry. One row per chapter, one
// canonical industry per row. Industries that previously aliased to the same
// chapter (e.g. brewers + softDrinks → ch.22) are not seeded — the most
// suitable industry wins the slot.
const CHAPTER_SEEDS: ChapterSeed[] = [
  { chapterNumber: 10, industry: TariffIndustryId.agriculturalProductsAndServices },
  { chapterNumber: 16, industry: TariffIndustryId.packagedFoodsAndMeats },
  { chapterNumber: 22, industry: TariffIndustryId.distillersAndVintners },
  { chapterNumber: 24, industry: TariffIndustryId.tobacco },
  { chapterNumber: 25, industry: TariffIndustryId.constructionMaterials },
  { chapterNumber: 26, industry: TariffIndustryId.diversifiedMetalsAndMining },
  { chapterNumber: 27, industry: TariffIndustryId.oilAndGasRefiningAndMarketing },
  { chapterNumber: 28, industry: TariffIndustryId.commodityChemicals },
  { chapterNumber: 30, industry: TariffIndustryId.pharmaceuticals },
  { chapterNumber: 31, industry: TariffIndustryId.fertilizersAndAgriculturalChemicals },
  { chapterNumber: 32, industry: TariffIndustryId.specialtyChemicals },
  { chapterNumber: 37, industry: TariffIndustryId.consumerElectronics },
  { chapterNumber: 38, industry: TariffIndustryId.diversifiedChemicals },
  { chapterNumber: 39, industry: TariffIndustryId.plastic },
  { chapterNumber: 40, industry: TariffIndustryId.tiresAndRubber },
  { chapterNumber: 44, industry: TariffIndustryId.forestProducts },
  { chapterNumber: 48, industry: TariffIndustryId.paperProducts },
  { chapterNumber: 49, industry: TariffIndustryId.commercialPrinting },
  { chapterNumber: 52, industry: TariffIndustryId.textiles },
  { chapterNumber: 62, industry: TariffIndustryId.apparelandaccessories },
  { chapterNumber: 64, industry: TariffIndustryId.footwear },
  { chapterNumber: 70, industry: TariffIndustryId.metalGlassPlasticContainers },
  { chapterNumber: 72, industry: TariffIndustryId.ironandsteel },
  { chapterNumber: 74, industry: TariffIndustryId.copper },
  { chapterNumber: 76, industry: TariffIndustryId.aluminium },
  { chapterNumber: 82, industry: TariffIndustryId.housewaresAndSpecialties },
  { chapterNumber: 84, industry: TariffIndustryId.industrialMachineryAndSupplies },
  { chapterNumber: 85, industry: TariffIndustryId.electricalcomponentsandequipment },
  { chapterNumber: 86, industry: TariffIndustryId.constructionMachineryAndHeavyTransportationEquipment },
  { chapterNumber: 87, industry: TariffIndustryId.automobiles },
  { chapterNumber: 88, industry: TariffIndustryId.aerospaceAndDefense },
  { chapterNumber: 90, industry: TariffIndustryId.healthCareEquipment },
  { chapterNumber: 94, industry: TariffIndustryId.homefurnishings },
  { chapterNumber: 95, industry: TariffIndustryId.leisureProducts },
];

// JSON value cast to jsonb. Single quotes inside JSON are escaped per Postgres
// string literal rules (`'` -> `''`).
function toPgJsonb(value: unknown): string {
  const json = JSON.stringify(value ?? {});
  return `'${json.replace(/'/g, "''")}'::jsonb`;
}

async function main() {
  console.log(`Building seed SQL for ${CHAPTER_SEEDS.length} chapters...`);

  const lines: string[] = [
    '-- Generated by src/scripts/industry-tariff-reports/seed-tariff-chapter-reports.ts',
    '-- Apply with: psql "$DATABASE_URL" -f prisma/seeds/tariff-chapter-reports.sql',
    '',
    'BEGIN;',
    '',
  ];

  for (const seed of CHAPTER_SEEDS) {
    const chapter = HTS_CHAPTERS[seed.chapterNumber];
    if (!chapter) {
      throw new Error(`HTS chapter ${seed.chapterNumber} not found in HTS_CHAPTERS`);
    }

    console.log(`  • chapter ${seed.chapterNumber} ← ${seed.industry}`);

    const [introduction, tariffUpdates, understandIndustry, industryAreas, conclusion] = await Promise.all([
      readReportCoverFromFile(seed.industry),
      readTariffUpdatesFromFile(seed.industry),
      readUnderstandIndustryJsonFromFile(seed.industry),
      readIndustryHeadingsFromFile(seed.industry),
      readFinalConclusionFromFile(seed.industry),
    ]);

    if (!introduction) console.warn(`    ! ${seed.industry}: missing report-cover.json`);
    if (!tariffUpdates) console.warn(`    ! ${seed.industry}: missing tariff-updates.json`);
    if (!understandIndustry) console.warn(`    ! ${seed.industry}: missing understand-industry.json`);
    if (!industryAreas) console.warn(`    ! ${seed.industry}: missing industry-headings.json`);
    if (!conclusion) console.warn(`    ! ${seed.industry}: missing final-conclusion.json`);

    const id = randomUUID();
    const slug = chapterUrlSlug(chapter);

    lines.push(
      `-- chapter ${seed.chapterNumber} (${chapter.shortName}) — content from ${seed.industry}`,
      `INSERT INTO tariff_chapter_reports (`,
      `  id, chapter_id, slug, old_url, introduction, tariff_updates, understand_industry, industry_areas, conclusion, space_id, updated_at`,
      `)`,
      `SELECT`,
      `  '${id}',`,
      `  c.id,`,
      `  '${slug}',`,
      `  '${seed.industry}',`,
      `  ${toPgJsonb(introduction)},`,
      `  ${toPgJsonb(tariffUpdates)},`,
      `  ${toPgJsonb(understandIndustry)},`,
      `  ${toPgJsonb(industryAreas)},`,
      `  ${toPgJsonb(conclusion)},`,
      `  'koala_gains',`,
      `  NOW()`,
      `FROM tariff_chapters c`,
      `WHERE c.number = ${seed.chapterNumber} AND c.space_id = 'koala_gains'`,
      `ON CONFLICT (space_id, chapter_id) DO UPDATE SET`,
      `  slug = EXCLUDED.slug,`,
      `  old_url = EXCLUDED.old_url,`,
      `  introduction = EXCLUDED.introduction,`,
      `  tariff_updates = EXCLUDED.tariff_updates,`,
      `  understand_industry = EXCLUDED.understand_industry,`,
      `  industry_areas = EXCLUDED.industry_areas,`,
      `  conclusion = EXCLUDED.conclusion,`,
      `  updated_at = NOW();`,
      ''
    );
  }

  lines.push('COMMIT;', '');

  const here = path.dirname(fileURLToPath(import.meta.url));
  const outDir = path.resolve(here, '../../../prisma/seeds');
  const outPath = path.join(outDir, 'tariff-chapter-reports.sql');
  await mkdir(outDir, { recursive: true });
  await writeFile(outPath, lines.join('\n'), 'utf8');

  console.log(`\nWrote ${lines.length} lines → ${outPath}`);
  console.log(`Apply with: psql "$DATABASE_URL" -f prisma/seeds/tariff-chapter-reports.sql`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
