// Generates UPDATE SQL that fills the `seo_details` column on
// `tariff_chapter_reports` for the 41 legacy industries.
//
// Assumes the row-level seed has already been applied so each industry's
// row exists (matched by `old_url = <industryId>`); this script only
// writes the SEO blob into that pre-existing row. Chapters without an
// industry (slug-only rows) are skipped — they have no SEO source.
//
// Source: each industry's `08-seo-details/seo-details.json` file in S3
// (the same shape the runtime already consumes — `TariffReportSeoDetails`
// in tariff-types.ts).
//
// Output: prisma/seeds/tariff-chapter-reports-seo.sql (apply with psql).
//
// Run with:
//   yarn tsx src/scripts/industry-tariff-reports/seed-tariff-chapter-reports-seo.ts
import 'dotenv/config';
import { writeFile, mkdir } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { readSeoDetailsFromFile } from '@/scripts/industry-tariff-reports/tariff-report-read-write';
import { TariffIndustryId } from '@/scripts/industry-tariff-reports/tariff-industries';

function toPgJsonb(value: unknown): string {
  const json = JSON.stringify(value ?? {});
  return `'${json.replace(/'/g, "''")}'::jsonb`;
}

function escapeSqlLiteral(value: string): string {
  return value.replace(/'/g, "''");
}

async function main() {
  const industries = Object.values(TariffIndustryId);
  console.log(`Building SEO update SQL for ${industries.length} industries...`);

  const lines: string[] = [
    '-- Generated by src/scripts/industry-tariff-reports/seed-tariff-chapter-reports-seo.ts',
    '-- Apply with: psql "$DATABASE_URL" -f prisma/seeds/tariff-chapter-reports-seo.sql',
    '--',
    '-- Updates the `seo_details` column on `tariff_chapter_reports` for the 41',
    '-- legacy industries. Rows are matched by `old_url`; rows without `old_url`',
    '-- (slug-only chapters) are not touched.',
    '',
    'BEGIN;',
    '',
  ];

  let withSeo = 0;
  let missing = 0;

  for (const industryId of industries) {
    const seoDetails = await readSeoDetailsFromFile(industryId);

    if (!seoDetails) {
      console.warn(`  ! ${industryId}: missing seo-details.json — skipping`);
      missing++;
      lines.push(`-- ${industryId}: no seo-details.json in S3, skipping`, '');
      continue;
    }

    console.log(`  • ${industryId}`);
    withSeo++;

    lines.push(
      `-- ${industryId}`,
      `UPDATE tariff_chapter_reports`,
      `SET seo_details = ${toPgJsonb(seoDetails)},`,
      `    updated_at = NOW()`,
      `WHERE space_id = 'koala_gains' AND old_url = '${escapeSqlLiteral(industryId)}';`,
      ''
    );
  }

  lines.push('COMMIT;', '');

  const here = path.dirname(fileURLToPath(import.meta.url));
  const outDir = path.resolve(here, '../../../prisma/seeds');
  const outPath = path.join(outDir, 'tariff-chapter-reports-seo.sql');
  await mkdir(outDir, { recursive: true });
  await writeFile(outPath, lines.join('\n'), 'utf8');

  console.log(`\nWrote ${lines.length} lines → ${outPath}`);
  console.log(`  ${withSeo} industries with SEO, ${missing} missing`);
  console.log(`Apply with: psql "$DATABASE_URL" -f prisma/seeds/tariff-chapter-reports-seo.sql`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
