// Generates UPDATE SQL that fills the `executive_summary` and
// `industry_areas_sections` columns on `tariff_chapter_reports` for the
// 41 legacy industries.
//
// Assumes the row-level seed has already been applied so each industry's
// row exists (matched by `old_url = <industryId>`); this script only
// writes those two blobs into the pre-existing row. Chapters without an
// industry (slug-only rows) are skipped — they have no S3 source.
//
// Sources:
//   executive_summary       ← `01-executive-summary/executive-summary.json` (ExecutiveSummary)
//   industry_areas_sections ← `05-industry-areas-section/industry-area.json` (IndustryAreaSection)
// Both shapes are defined in tariff-types.ts.
//
// Output: prisma/seeds/tariff-chapter-reports-executive-and-areas.sql
//
// Run with:
//   yarn tsx src/scripts/industry-tariff-reports/seed-tariff-chapter-reports-executive-and-areas.ts
import 'dotenv/config';
import { writeFile, mkdir } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { readExecutiveSummaryFromFile, readIndustryAreaSectionFromFile } from '@/scripts/industry-tariff-reports/tariff-report-read-write';
import { TariffIndustryId } from '@/scripts/industry-tariff-reports/tariff-industries';

function toPgJsonb(value: unknown): string {
  const json = JSON.stringify(value ?? {});
  return `'${json.replace(/'/g, "''")}'::jsonb`;
}

function escapeSqlLiteral(value: string): string {
  return value.replace(/'/g, "''");
}

async function main() {
  const industries = Object.values(TariffIndustryId);
  console.log(`Building executive_summary + industry_areas_sections update SQL for ${industries.length} industries...`);

  const lines: string[] = [
    '-- Generated by src/scripts/industry-tariff-reports/seed-tariff-chapter-reports-executive-and-areas.ts',
    '-- Apply with: psql "$DATABASE_URL" -f prisma/seeds/tariff-chapter-reports-executive-and-areas.sql',
    '--',
    '-- Updates `executive_summary` and `industry_areas_sections` on `tariff_chapter_reports`',
    '-- for the 41 legacy industries. Rows are matched by `old_url`; rows without `old_url`',
    '-- (slug-only chapters) are not touched.',
    '',
    'BEGIN;',
    '',
  ];

  let withBoth = 0;
  let withOnlyExec = 0;
  let withOnlyAreas = 0;
  let missing = 0;

  for (const industryId of industries) {
    const [executiveSummary, industryAreasSections] = await Promise.all([
      readExecutiveSummaryFromFile(industryId),
      readIndustryAreaSectionFromFile(industryId),
    ]);

    if (!executiveSummary && !industryAreasSections) {
      console.warn(`  ! ${industryId}: missing both executive-summary.json and industry-area.json — skipping`);
      missing++;
      lines.push(`-- ${industryId}: no executive-summary.json or industry-area.json in S3, skipping`, '');
      continue;
    }

    if (executiveSummary && industryAreasSections) {
      console.log(`  • ${industryId}`);
      withBoth++;
    } else if (executiveSummary) {
      console.log(`  • ${industryId} (only executive-summary)`);
      withOnlyExec++;
    } else {
      console.log(`  • ${industryId} (only industry-areas-sections)`);
      withOnlyAreas++;
    }

    const setClauses: string[] = [];
    if (executiveSummary) setClauses.push(`executive_summary = ${toPgJsonb(executiveSummary)}`);
    if (industryAreasSections) setClauses.push(`industry_areas_sections = ${toPgJsonb(industryAreasSections)}`);
    setClauses.push('updated_at = NOW()');

    lines.push(
      `-- ${industryId}`,
      `UPDATE tariff_chapter_reports`,
      `SET ${setClauses.join(',\n    ')}`,
      `WHERE space_id = 'koala_gains' AND old_url = '${escapeSqlLiteral(industryId)}';`,
      ''
    );
  }

  lines.push('COMMIT;', '');

  const here = path.dirname(fileURLToPath(import.meta.url));
  const outDir = path.resolve(here, '../../../prisma/seeds');
  const outPath = path.join(outDir, 'tariff-chapter-reports-executive-and-areas.sql');
  await mkdir(outDir, { recursive: true });
  await writeFile(outPath, lines.join('\n'), 'utf8');

  console.log(`\nWrote ${lines.length} lines → ${outPath}`);
  console.log(`  ${withBoth} industries with both, ${withOnlyExec} only-executive, ${withOnlyAreas} only-areas, ${missing} missing`);
  console.log(`Apply with: psql "$DATABASE_URL" -f prisma/seeds/tariff-chapter-reports-executive-and-areas.sql`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
