/**
 * Commodities report-type domain model.
 *
 * A commodity (crude oil, gold, wheat…) is analyzed on its own, mirroring the
 * ETF report shape: 4 scored categories + a non-scored Key Facts section + a
 * Final Summary.
 *
 * Report content is authored as static JSON — one file per commodity slug under
 * `src/commodity-data/reports/<slug>.json` — instead of being generated by an
 * LLM and stored in the database. These interfaces are the single source of
 * truth for the shape of those JSON files and of the data the report pages
 * consume. See `src/commodity-data/README.md` for how to add a new commodity.
 */

/** The four scored analysis categories. Values match the `categoryKey` in the report JSON. */
export enum CommodityAnalysisCategory {
  SupplyAndDemand = 'SupplyAndDemand',
  PriceAndValue = 'PriceAndValue',
  VolatilityAndRisk = 'VolatilityAndRisk',
  FutureOutlook = 'FutureOutlook',
}

/** URL slug for each scored category subpage under `/commodities/[slug]/`. */
export const COMMODITY_CATEGORY_TO_PATH: Record<CommodityAnalysisCategory, string> = {
  [CommodityAnalysisCategory.SupplyAndDemand]: 'supply-and-demand',
  [CommodityAnalysisCategory.PriceAndValue]: 'price-and-value',
  [CommodityAnalysisCategory.VolatilityAndRisk]: 'volatility-and-risk',
  [CommodityAnalysisCategory.FutureOutlook]: 'future-outlook',
};

/** Human-readable category names, used by the radar chart and section headings. */
export const COMMODITY_CATEGORY_NAMES: Record<CommodityAnalysisCategory, string> = {
  [CommodityAnalysisCategory.SupplyAndDemand]: 'Supply & Demand',
  [CommodityAnalysisCategory.PriceAndValue]: 'Price & Value',
  [CommodityAnalysisCategory.VolatilityAndRisk]: 'Volatility & Risk',
  [CommodityAnalysisCategory.FutureOutlook]: 'Future Outlook',
};

/** A single analysis factor definition (flat — commodities have no group logic). */
export interface CommodityFactorDefinition {
  factorKey: string;
  factorTitle: string;
  factorDescription: string;
  factorMetrics?: string;
}

export interface CommodityCategoryFactorsConfig {
  categoryKey: CommodityAnalysisCategory;
  categoryName: string;
  categoryDescription: string;
  factors: CommodityFactorDefinition[];
}

/** Pass/Fail is the only verdict a factor or flag can carry. */
export type CommodityEvaluationResult = 'Pass' | 'Fail';

/** One green/red flag assessed for a specific commodity. */
export interface CommodityKeyFactsFlag {
  flag: string;
  explanation: string;
  result: CommodityEvaluationResult;
}

export interface CommodityKeyFactsProducer {
  country: string;
  /** Approximate share of global production, e.g. "~13%". Optional. */
  share?: string;
}

export interface CommodityKeyFactsWayToInvest {
  /** e.g. ETF, Futures, Physical, Equities. */
  type: string;
  /** A representative instrument, e.g. an ETF ticker. */
  name: string;
  /** Optional short note. */
  note?: string;
}

/** The Overview / Key Facts block of a commodity report. */
export interface CommodityKeyFacts {
  /** Two plain-prose paragraphs (separated by a blank line). */
  keyFacts: string;
  greenFlags: CommodityKeyFactsFlag[];
  redFlags: CommodityKeyFactsFlag[];
  mainUses: string[];
  topProducers: CommodityKeyFactsProducer[];
  waysToInvest: CommodityKeyFactsWayToInvest[];
}

/** One factor verdict within a scored category. */
export interface CommodityFactorResult {
  factorKey: string;
  oneLineExplanation: string;
  detailedExplanation: string;
  result: CommodityEvaluationResult;
}

/** One scored category (supply & demand, price & value, …) of a commodity report. */
export interface CommodityCategoryResult {
  categoryKey: CommodityAnalysisCategory;
  /** Short executive summary shown at the top of the category page. */
  summary: string;
  /** Longer markdown analysis for the category. */
  overallAnalysisDetails: string;
  factors: CommodityFactorResult[];
}

/** Basic descriptive fields for a commodity (the `commodities.json` listing rows). */
export interface CommodityBasicInfo {
  slug: string;
  name: string;
  commodityGroup: string;
  priceSymbol?: string | null;
  exchange?: string | null;
  unit?: string | null;
  currency: string;
}

/**
 * A full commodity report as authored in `src/commodity-data/reports/<slug>.json`.
 * Extends the basic descriptive fields with the generated-style content
 * (summary, meta description, key facts, and the four scored categories).
 */
export interface CommodityReportJson extends CommodityBasicInfo {
  /** Final-summary prose shown on the main report page. */
  summary: string | null;
  /** SEO meta description; falls back to a generated one when null. */
  metaDescription: string | null;
  /** ISO date the report content was last authored/updated. */
  updatedAt: string;
  keyFacts: CommodityKeyFacts | null;
  /** The scored categories that have been authored (0-4). */
  categories: CommodityCategoryResult[];
}
