import { prisma } from '@/prisma';
import { LLMProvider } from '@/types/llmConstants';
import { GenerationRequestStatus } from '@/types/ticker-typesv1';
import { CLAUDE_AUTO_GEN } from '@/util/claude/claude-usage-constants';
import { getClaudeSubscriptionUsage } from '@/util/claude/claude-usage';
import { getAutoGenModePreset, isStockAutoGenEnabled, isWithinAutoGenWindow } from '@/utils/analysis-reports/auto-gen-config';
import { AutoEnqueueResult, evaluateAutoGenGates } from '@/utils/analysis-reports/auto-gen-gate-utils';
import { ALL_SECTIONS_REGENERATE_FLAGS, upsertGenerationRequest } from '@/utils/analysis-reports/generation-request-utils';
import { getOldestStocksOverall } from '@/utils/oldest-reports-utils';

/**
 * Claude-usage-gated stock report auto-generation (enqueue side).
 *
 * A cron hits the `enqueue-auto-stock-generation` route every 15 min, 24/7. Each
 * call is gated by the App Settings controls: the GENERATION_ENTITY must include
 * stocks, the current ET time must fall inside the selected GENERATION_WINDOW, and
 * the Claude usage gates for the selected GENERATION_MODE must pass. When all pass
 * AND no auto requests are open, it creates one small batch (the mode's batch size)
 * of generate-all requests for the oldest stocks. The existing ~3-min processor
 * then generates them normally.
 */

/**
 * See the module doc. Never throws — on any failure it creates nothing (fails closed).
 */
export async function enqueueAutoStockGenerationBatch(spaceId: string): Promise<AutoEnqueueResult> {
  const now = new Date();
  try {
    if (!(await isStockAutoGenEnabled())) {
      return { created: 0, reason: 'entity-disabled', fiveHourPct: null, weeklyPct: null };
    }
    if (!(await isWithinAutoGenWindow(now))) {
      return { created: 0, reason: 'outside-window', fiveHourPct: null, weeklyPct: null };
    }

    const preset = await getAutoGenModePreset();
    const usage = await getClaudeSubscriptionUsage();
    const gate = evaluateAutoGenGates(usage, now, preset);
    if (!gate.allowed) {
      return { created: 0, reason: gate.reason, fiveHourPct: gate.fiveHourPct, weeklyPct: gate.weeklyPct };
    }

    // Create a fresh batch ONLY when no auto requests are open (never top up a
    // partial batch) — this bounds the concurrent Claude fan-out.
    const openAutoCount = await prisma.tickerV1GenerationRequest.count({
      where: {
        spaceId,
        autoGenerated: true,
        status: { in: [GenerationRequestStatus.NotStarted, GenerationRequestStatus.InProgress] },
      },
    });

    if (openAutoCount > 0) {
      return { created: 0, reason: 'batch-in-progress', fiveHourPct: gate.fiveHourPct, weeklyPct: gate.weeklyPct };
    }

    const oldest = await getOldestStocksOverall(spaceId, preset.batchSize);
    let created = 0;
    for (const stock of oldest) {
      await upsertGenerationRequest({
        tickerId: stock.tickerId,
        flags: ALL_SECTIONS_REGENERATE_FLAGS,
        llmProvider: LLMProvider.CLAUDE,
        llmModel: CLAUDE_AUTO_GEN.LLM_MODEL,
        autoGenerated: true,
      });
      created++;
    }

    return { created, reason: 'enqueued-batch', fiveHourPct: gate.fiveHourPct, weeklyPct: gate.weeklyPct };
  } catch (err) {
    console.warn('enqueueAutoStockGenerationBatch failed; created nothing this run.', err);
    return { created: 0, reason: 'error', fiveHourPct: null, weeklyPct: null };
  }
}
