import { prisma } from '@/prisma';
import { GenerationRequestStatus } from '@/types/ticker-typesv1';
import { TickerV1GenerationRequest } from '@prisma/client';

/**
 * The nine report sections that make up a full stock report, as `regenerate*`
 * flags. Shared by the admin generation-requests POST route and the nightly
 * auto-generation job so both create identical requests.
 */
export interface RegenerateFlags {
  regenerateCompetition: boolean;
  regenerateFinancialAnalysis: boolean;
  regenerateBusinessAndMoat: boolean;
  regeneratePastPerformance: boolean;
  regenerateFutureGrowth: boolean;
  regenerateFairValue: boolean;
  regenerateManagementTeam: boolean;
  regenerateStability: boolean;
  regenerateFinalSummary: boolean;
}

/** All sections on — used by the nightly job's "generate-all" requests. */
export const ALL_SECTIONS_REGENERATE_FLAGS: RegenerateFlags = {
  regenerateCompetition: true,
  regenerateFinancialAnalysis: true,
  regenerateBusinessAndMoat: true,
  regeneratePastPerformance: true,
  regenerateFutureGrowth: true,
  regenerateFairValue: true,
  regenerateManagementTeam: true,
  regenerateStability: true,
  regenerateFinalSummary: true,
};

export interface UpsertGenerationRequestInput {
  tickerId: string;
  flags: RegenerateFlags;
  /** Provider/model override; null/undefined = use configured defaults. */
  llmProvider?: string | null;
  llmModel?: string | null;
  /** Marks the request as created by the nightly auto-generation job. */
  autoGenerated?: boolean;
}

/**
 * Creates a NotStarted generation request for a ticker, or updates the existing
 * NotStarted one (OR-ing in the requested sections). This is the exact behaviour
 * the generation-requests POST route used inline; extracted so the nightly
 * auto-generation job reuses it instead of duplicating the create logic.
 */
/** Which of these generation requests (stock or ETF) were paid for with a credit. */
export async function findPaidGenerationRequestIds(generationRequestIds: string[]): Promise<Set<string>> {
  if (generationRequestIds.length === 0) {
    return new Set();
  }
  const spends = await prisma.reportSpend.findMany({ where: { generationRequestId: { in: generationRequestIds } }, select: { generationRequestId: true } });
  return new Set(spends.map((spend) => spend.generationRequestId));
}

export async function upsertGenerationRequest(input: UpsertGenerationRequestInput): Promise<TickerV1GenerationRequest> {
  const { tickerId, flags } = input;

  const notStarted = await prisma.tickerV1GenerationRequest.findMany({
    where: { tickerId, status: GenerationRequestStatus.NotStarted },
    orderBy: { createdAt: 'desc' },
  });
  // A request a user paid for (it has a report_spends row) is never merged into
  // or re-pointed at another provider/model: admin and nightly work gets its own request.
  const paidIds = await findPaidGenerationRequestIds(notStarted.map((request) => request.id));
  const existing = notStarted.find((request) => !paidIds.has(request.id));

  if (existing) {
    return prisma.tickerV1GenerationRequest.update({
      where: { id: existing.id },
      data: {
        regenerateCompetition: flags.regenerateCompetition || existing.regenerateCompetition,
        regenerateFinancialAnalysis: flags.regenerateFinancialAnalysis || existing.regenerateFinancialAnalysis,
        regenerateBusinessAndMoat: flags.regenerateBusinessAndMoat || existing.regenerateBusinessAndMoat,
        regeneratePastPerformance: flags.regeneratePastPerformance || existing.regeneratePastPerformance,
        regenerateFutureGrowth: flags.regenerateFutureGrowth || existing.regenerateFutureGrowth,
        regenerateFairValue: flags.regenerateFairValue || existing.regenerateFairValue,
        regenerateManagementTeam: flags.regenerateManagementTeam || existing.regenerateManagementTeam,
        regenerateStability: flags.regenerateStability || existing.regenerateStability,
        regenerateFinalSummary: flags.regenerateFinalSummary || existing.regenerateFinalSummary,
        // A newly-supplied provider/model overrides the pending request; otherwise keep the existing choice.
        llmProvider: input.llmProvider ?? existing.llmProvider,
        llmModel: input.llmModel ?? existing.llmModel,
        autoGenerated: input.autoGenerated || existing.autoGenerated,
        updatedAt: new Date(),
      },
    });
  }

  return prisma.tickerV1GenerationRequest.create({
    data: {
      tickerId,
      regenerateCompetition: flags.regenerateCompetition,
      regenerateFinancialAnalysis: flags.regenerateFinancialAnalysis,
      regenerateBusinessAndMoat: flags.regenerateBusinessAndMoat,
      regeneratePastPerformance: flags.regeneratePastPerformance,
      regenerateFutureGrowth: flags.regenerateFutureGrowth,
      regenerateFairValue: flags.regenerateFairValue,
      regenerateManagementTeam: flags.regenerateManagementTeam,
      regenerateStability: flags.regenerateStability,
      regenerateFinalSummary: flags.regenerateFinalSummary,
      llmProvider: input.llmProvider ?? null,
      llmModel: input.llmModel ?? null,
      autoGenerated: input.autoGenerated ?? false,
    },
  });
}
