rm-files:
	aws s3 rm s3://dodao-dev-public-assets/unzipped/ --recursive
	aws s3 rm s3://dodao-dev-public-assets/test/ --recursive

upload-file:
	aws s3 cp "Alchemix(10_24_2024 6_12_23 PM).zip" s3://dodao-dev-public-assets/test/
