import { prisma } from '@/prisma';
import { KoalaGainsSpaceId } from '@/types/koalaGainsConstants';
import { TickerV1GenerationRequestWithTicker } from '@/types/public-equity/analysis-factors-types';
import { GenerationRequestStatus, ReportType } from '@/types/ticker-typesv1';
import { runAutoStockGenerationTick } from '@/utils/analysis-reports/auto-stock-generation-utils';
import { triggerGenerationOfAReportSimplified } from '@/utils/analysis-reports/generation-report-utils';
import { markAsCompleted } from '@/utils/analysis-reports/report-status-utils';
import { calculatePendingSteps } from '@/utils/analysis-reports/report-steps-statuses';
import { withErrorHandlingV2 } from '@dodao/web-core/api/helpers/middlewares/withErrorHandling';
import { TickerV1GenerationRequest } from '@prisma/client';
import { NextRequest } from 'next/server';

interface GenerationRequestsResponse {
  inProgressRequests: (TickerV1GenerationRequest & { pendingSteps: ReportType[] })[];
  justStartedRequests: TickerV1GenerationRequest[];
  requests: TickerV1GenerationRequestWithTicker[];
  processedCount: number;
  message: string;
}

async function getInProgressRequests() {
  return await prisma.tickerV1GenerationRequest.findMany({
    where: {
      spaceId: KoalaGainsSpaceId,
      status: GenerationRequestStatus.InProgress,
    },
    include: {
      ticker: {
        select: {
          symbol: true,
          exchange: true,
        },
      },
    },
  });
}

async function getHandler(req: NextRequest, { params }: { params: Promise<{ spaceId: string }> }): Promise<GenerationRequestsResponse> {
  const { spaceId } = await params;

  // Nightly Claude auto-generation hooks into this same ~3-min tick: if we're in
  // the off-hours window and under budget it seeds a fresh batch of auto requests
  // (only when none are open). `autoAllowed` tells us whether auto requests may be
  // processed this tick; admin requests are never gated. Never throws.
  const autoTick = await runAutoStockGenerationTick(spaceId);

  // First, check how many InProgress requests exist
  let inProgressRequests = await getInProgressRequests();

  for (const request of inProgressRequests) {
    const allStepsCompleted = calculatePendingSteps(request).length === 0;
    if (allStepsCompleted) {
      await markAsCompleted(request);
    }
  }

  inProgressRequests = await getInProgressRequests();

  // Calculate how many NotStarted requests we can fetch (max 10 total)
  const maxNotStartedRequests = 10 - inProgressRequests.length;

  // Get NotStarted requests with ticker information
  const notStartedRequests = await prisma.tickerV1GenerationRequest.findMany({
    where: {
      spaceId,
      status: GenerationRequestStatus.NotStarted,
    },
    include: {
      ticker: {
        select: {
          symbol: true,
          exchange: true,
        },
      },
    },
    orderBy: {
      createdAt: 'desc',
    },
    take: maxNotStartedRequests,
  });

  let processedCount = 0;
  const processedRequests: TickerV1GenerationRequestWithTicker[] = [];

  // Loop through each request
  for (const request of [...inProgressRequests, ...notStartedRequests]) {
    // Auto-generated (nightly) requests are only processed when the pacing gate
    // passed this tick. Admin requests always process. Skipped auto requests stay
    // as-is and are retried on a later in-window tick.
    if (request.autoGenerated && !autoTick.autoAllowed) {
      continue;
    }

    try {
      console.log(`Processing request ${request.id} for ticker ${request.ticker.symbol} on exchange ${request.ticker.exchange}`);
      await triggerGenerationOfAReportSimplified(request.ticker.symbol, request.ticker.exchange, request.id);

      // Get the updated request to include in the response
      const updatedRequest = await prisma.tickerV1GenerationRequest.findUnique({
        where: { id: request.id },
        include: {
          ticker: {
            select: {
              symbol: true,
              exchange: true,
              name: true,
              industry: {
                select: {
                  name: true,
                  industryKey: true,
                },
              },
              subIndustry: {
                select: {
                  name: true,
                  subIndustryKey: true,
                },
              },
            },
          },
        },
      });

      if (updatedRequest) {
        // Add pending steps to the request
        const requestWithPendingSteps = {
          ...updatedRequest,
          pendingSteps: calculatePendingSteps(updatedRequest),
        };

        processedRequests.push(requestWithPendingSteps as TickerV1GenerationRequestWithTicker);
        processedCount++;
      }
    } catch (error) {
      console.error(`Error processing request ${request.id}:`, error);
    }
  }

  return {
    inProgressRequests: inProgressRequests.map((r) => {
      return {
        ...r,
        pendingSteps: calculatePendingSteps(r),
      };
    }),
    justStartedRequests: notStartedRequests,
    requests: processedRequests,
    processedCount,
    message:
      `Processed ${processedCount} out of ${notStartedRequests.length} requests. ${inProgressRequests.length} requests were already in progress. ` +
      `Auto-gen: allowed=${autoTick.autoAllowed} created=${autoTick.created} reason=${autoTick.reason}` +
      (autoTick.fiveHourPct !== null ? ` 5h=${autoTick.fiveHourPct}% weekly=${autoTick.weeklyPct ?? '?'}%` : ''),
  };
}

export const GET = withErrorHandlingV2<GenerationRequestsResponse>(getHandler);
