import { ShortVideoFragment } from '@/graphql/generated/generated-types';

export const videos: ShortVideoFragment[] = [
  {
    id: '1',
    thumbnail: 'https://i.ytimg.com/vi/NHxjypDc4xw/oar1.jpg',
    title: 'What is Dodao',
    description: 'Blockchain',
    videoUrl: 'https://dodao-prod-public-assets.s3.amazonaws.com/testing/Iluvium_PvP.mp4',
    priority: 50,
  },
  {
    id: '2',
    thumbnail: 'https://i.ytimg.com/vi/vEyNb7D5gb0/oar1.jpg',
    title: 'What is leverage',
    description: 'Blockchain',
    videoUrl: 'https://dodao-prod-public-assets.s3.amazonaws.com/testing/GMX_V2.mp4',
    priority: 50,
  },
  {
    id: '3',
    thumbnail: 'https://i.ytimg.com/vi/vEyNb7D5gb0/oar1.jpg',
    title: 'What is leverage',
    description: 'Blockchain',
    videoUrl: 'https://dodao-prod-public-assets.s3.amazonaws.com/testing/Intro_To_Uniswap_X.mp4',
    priority: 50,
  },
  {
    id: '4',
    thumbnail: 'https://i.ytimg.com/vi/vEyNb7D5gb0/oar1.jpg',
    title: 'What is leverage',
    description: 'Blockchain',
    videoUrl: 'https://dodao-prod-public-assets.s3.amazonaws.com/testing/Uniswap_V4.mp4',
    priority: 50,
  },
  {
    id: '5',
    thumbnail: 'https://i.ytimg.com/vi/vEyNb7D5gb0/oar1.jpg',
    title: 'What is leverage',
    description: 'Blockchain',
    videoUrl: 'https://dodao-prod-public-assets.s3.amazonaws.com/testing/Why_everyone_is_talking_about_ERC-4337.mp4',
    priority: 50,
  },
  {
    id: '6',
    thumbnail: 'https://i.ytimg.com/vi/NHxjypDc4xw/oar1.jpg',
    title: 'What is Dodao',
    description: 'Blockchain',
    videoUrl: 'https://dodao-prod-public-assets.s3.amazonaws.com/testing/Iluvium_PvP.mp4',
    priority: 50,
  },
  {
    id: '7',
    thumbnail: 'https://i.ytimg.com/vi/vEyNb7D5gb0/oar1.jpg',
    title: 'What is leverage',
    description: 'Blockchain',
    videoUrl: 'https://dodao-prod-public-assets.s3.amazonaws.com/testing/GMX_V2.mp4',
    priority: 50,
  },
  {
    id: '8',
    thumbnail: 'https://i.ytimg.com/vi/vEyNb7D5gb0/oar1.jpg',
    title: 'What is leverage',
    description: 'Blockchain',
    videoUrl: 'https://dodao-prod-public-assets.s3.amazonaws.com/testing/Intro_To_Uniswap_X.mp4',
    priority: 50,
  },
  {
    id: '9',
    thumbnail: 'https://i.ytimg.com/vi/vEyNb7D5gb0/oar1.jpg',
    title: 'What is leverage',
    description: 'Blockchain',
    videoUrl: 'https://dodao-prod-public-assets.s3.amazonaws.com/testing/Uniswap_V4.mp4',
    priority: 50,
  },
  {
    id: '10',
    thumbnail: 'https://i.ytimg.com/vi/vEyNb7D5gb0/oar1.jpg',
    title: 'What is leverage',
    description: 'Blockchain',
    videoUrl: 'https://dodao-prod-public-assets.s3.amazonaws.com/testing/Why_everyone_is_talking_about_ERC-4337.mp4',
    priority: 50,
  },
];
