import { prisma } from '@/prisma';
import { LLMProvider } from '@/types/llmConstants';
import { GenerationRequestStatus } from '@/types/ticker-typesv1';
import { getClaudeSubscriptionUsage } from '@/util/claude/claude-usage';
import { AutoEnqueueResult } from '@/utils/auto-generation/auto-gen-models';
import {
  chooseAutoGenModel,
  evaluateAutoGenGates,
  getAutoGenModePreset,
  isStockAutoGenEnabled,
  isWithinAutoGenWindow,
  isWithinFrequencyCooldown,
} from '@/utils/auto-generation/auto-gen-utils';
import { ALL_SECTIONS_REGENERATE_FLAGS, upsertGenerationRequest } from '@/utils/analysis-reports/generation-request-utils';
import { getOldestStocksOverall } from '@/utils/oldest-reports-utils';

/**
 * Claude-usage-gated stock report auto-generation (enqueue side).
 *
 * Called every few minutes by the `/cron/heartbeat` job (via
 * `runAutoGenerationTick`). Each call is gated by the App Settings controls: the
 * GENERATION_ENTITY must include stocks, the current ET
 * time must fall inside the selected GENERATION_WINDOW, no auto batch may be open,
 * the mode's frequency cooldown must have elapsed since the last batch, and the
 * shared Claude usage gates must pass. When all pass it creates one batch (the
 * mode's batch size) of generate-all requests for the oldest stocks. The existing
 * ~3-min processor then generates them normally. The mode drives BOTH how many per
 * batch and how often batches run.
 */

/**
 * Number of stock auto-generation requests currently open (NotStarted or
 * InProgress). A non-zero count means a batch is still draining, so no new batch
 * is created. Shared by the enqueue job and the read-only status endpoint so both
 * read the same "batch in progress?" signal.
 */
export async function countOpenAutoStockRequests(spaceId: string): Promise<number> {
  return prisma.tickerV1GenerationRequest.count({
    where: {
      spaceId,
      autoGenerated: true,
      status: { in: [GenerationRequestStatus.NotStarted, GenerationRequestStatus.InProgress] },
    },
  });
}

/**
 * `updatedAt` of the most recent stock auto-generation request, or null when none
 * exists. Drives the mode's frequency cooldown. Shared by the enqueue job and the
 * status endpoint.
 */
export async function latestAutoStockRequestUpdatedAt(spaceId: string): Promise<Date | null> {
  const lastAuto = await prisma.tickerV1GenerationRequest.findFirst({
    where: { spaceId, autoGenerated: true },
    orderBy: { updatedAt: 'desc' },
    select: { updatedAt: true },
  });
  return lastAuto?.updatedAt ?? null;
}

/**
 * See the module doc. Never throws — on any failure it creates nothing (fails closed).
 */
export async function enqueueAutoStockGenerationBatch(spaceId: string): Promise<AutoEnqueueResult> {
  const now = new Date();
  try {
    if (!(await isStockAutoGenEnabled())) {
      return { created: 0, reason: 'entity-disabled', fiveHourPct: null, weeklyPct: null };
    }
    if (!(await isWithinAutoGenWindow(now))) {
      return { created: 0, reason: 'outside-window', fiveHourPct: null, weeklyPct: null };
    }

    const { batchSize, minMinutesBetweenBatches } = await getAutoGenModePreset();

    // Create a fresh batch ONLY when no auto requests are open (never top up a
    // partial batch) — this bounds the concurrent Claude fan-out.
    const openAutoCount = await countOpenAutoStockRequests(spaceId);
    if (openAutoCount > 0) {
      return { created: 0, reason: 'batch-in-progress', fiveHourPct: null, weeklyPct: null };
    }

    // Frequency lever: wait the mode's cooldown after the previous batch finished
    // (newest auto request's updatedAt) before starting the next one.
    const lastAutoAt = await latestAutoStockRequestUpdatedAt(spaceId);
    if (isWithinFrequencyCooldown(now, lastAutoAt, minMinutesBetweenBatches)) {
      return { created: 0, reason: 'frequency-cooldown', fiveHourPct: null, weeklyPct: null };
    }

    const usage = await getClaudeSubscriptionUsage();
    const gate = await evaluateAutoGenGates(usage, now);
    const gateFields = {
      fiveHourPct: gate.fiveHourPct,
      weeklyPct: gate.weeklyPct,
      remainingPct: gate.remainingPct,
      requiredRemainingPct: gate.requiredRemainingPct,
      hoursToReset: gate.hoursToReset,
      strategy: gate.strategy,
    };
    if (!gate.allowed) {
      return { created: 0, reason: gate.reason, ...gateFields };
    }

    const oldest = await getOldestStocksOverall(spaceId, batchSize);
    const autoGenModel = await chooseAutoGenModel(usage);
    let created = 0;
    for (const stock of oldest) {
      await upsertGenerationRequest({
        tickerId: stock.tickerId,
        flags: ALL_SECTIONS_REGENERATE_FLAGS,
        llmProvider: LLMProvider.CLAUDE,
        llmModel: autoGenModel,
        autoGenerated: true,
      });
      created++;
    }

    return { created, reason: 'enqueued-batch', ...gateFields, chosenModel: autoGenModel };
  } catch (err) {
    console.warn('enqueueAutoStockGenerationBatch failed; created nothing this run.', err);
    return { created: 0, reason: 'error', fiveHourPct: null, weeklyPct: null };
  }
}
