import { prisma } from '@/prisma';
import { LLMProvider } from '@/types/llmConstants';
import { EtfGenerationRequestStatus } from '@/types/etf/etf-analysis-types';
import { CLAUDE_AUTO_GEN } from '@/util/claude/claude-usage-constants';
import { getClaudeSubscriptionUsage } from '@/util/claude/claude-usage';
import { AutoEnqueueResult } from '@/utils/auto-generation/auto-gen-models';
import {
  evaluateAutoGenGates,
  getAutoGenThroughput,
  isEtfAutoGenEnabled,
  isWithinAutoGenWindow,
  isWithinFrequencyCooldown,
} from '@/utils/auto-generation/auto-gen-utils';
import { EtfCanadaExchanges, EtfUSExchanges } from '@/utils/etfCountryExchangeUtils';
import { ALL_ETF_SECTIONS_REGENERATE_FLAGS, upsertEtfGenerationRequest } from '@/utils/etf-analysis-reports/etf-generation-request-utils';
import { ensureMorDataForAnalysis } from '@/utils/etf-analysis-reports/mor-scrape-utils';

/**
 * Claude-usage-gated ETF report auto-generation (enqueue side).
 *
 * Mirrors the stock auto-generation job (`enqueueAutoStockGenerationBatch`) and
 * reuses the same gates. The difference is the selection: instead of the OLDEST
 * already-generated reports, this picks ETFs whose reports have NOT been
 * generated/tried yet, prioritized by country — US first, then Canada, then
 * everything else. Called every few minutes by the `/auto-generation/tick`
 * dispatcher (and by the `enqueue-auto-etf-generation` route for manual runs); the
 * existing ~3-min `generate-etf-v1-request` processor then generates whatever this
 * enqueues.
 */

const US_EXCHANGES: string[] = Object.values(EtfUSExchanges);
const CANADA_EXCHANGES: string[] = Object.values(EtfCanadaExchanges);

interface EtfToGenerate {
  id: string;
  symbol: string;
  exchange: string;
}

/**
 * ETFs that have never been generated or attempted — no category reports and no
 * generation request yet — returned up to `limit`, prioritized US → Canada →
 * other. Country is derived from the exchange (ETFs have no country column), so
 * each priority tier is a separate bounded query that fills the remaining slots.
 */
async function getEtfsMissingReports(spaceId: string, limit: number): Promise<EtfToGenerate[]> {
  const baseWhere = {
    spaceId,
    categoryAnalysisResults: { none: {} },
    generationRequests: { none: {} },
  };

  const tiers = [{ exchange: { in: US_EXCHANGES } }, { exchange: { in: CANADA_EXCHANGES } }, { exchange: { notIn: [...US_EXCHANGES, ...CANADA_EXCHANGES] } }];

  const selected: EtfToGenerate[] = [];
  for (const tier of tiers) {
    if (selected.length >= limit) break;
    const rows = await prisma.etf.findMany({
      where: { ...baseWhere, ...tier },
      orderBy: { symbol: 'asc' },
      take: limit - selected.length,
      select: { id: true, symbol: true, exchange: true },
    });
    selected.push(...rows);
  }

  return selected;
}

/**
 * When no auto batch is open, the mode's frequency cooldown has elapsed, and the
 * shared Claude usage gates pass, creates one batch (the mode's batch size) of
 * full-report Claude requests for ETFs missing their reports (US → Canada →
 * other). Called by the `enqueue-auto-etf-generation` route on a cron. Never throws
 * — on any failure it creates nothing (fails closed).
 */
export async function enqueueAutoEtfGenerationBatch(spaceId: string): Promise<AutoEnqueueResult> {
  const now = new Date();
  try {
    if (!(await isEtfAutoGenEnabled())) {
      return { created: 0, reason: 'entity-disabled', fiveHourPct: null, weeklyPct: null };
    }
    if (!(await isWithinAutoGenWindow(now))) {
      return { created: 0, reason: 'outside-window', fiveHourPct: null, weeklyPct: null };
    }

    const { batchSize, minMinutesBetweenBatches } = await getAutoGenThroughput();

    // Create a fresh batch ONLY when no auto requests are open (never top up a
    // partial batch) — this bounds the concurrent Claude fan-out.
    const openAutoCount = await prisma.etfGenerationRequest.count({
      where: {
        spaceId,
        autoGenerated: true,
        status: { in: [EtfGenerationRequestStatus.NotStarted, EtfGenerationRequestStatus.InProgress] },
      },
    });
    if (openAutoCount > 0) {
      return { created: 0, reason: 'batch-in-progress', fiveHourPct: null, weeklyPct: null };
    }

    // Frequency lever: wait the effective cooldown after the previous batch finished
    // (newest auto request's updatedAt) before starting the next one.
    const lastAuto = await prisma.etfGenerationRequest.findFirst({
      where: { spaceId, autoGenerated: true },
      orderBy: { updatedAt: 'desc' },
      select: { updatedAt: true },
    });
    if (isWithinFrequencyCooldown(now, lastAuto?.updatedAt ?? null, minMinutesBetweenBatches)) {
      return { created: 0, reason: 'frequency-cooldown', fiveHourPct: null, weeklyPct: null };
    }

    const usage = await getClaudeSubscriptionUsage();
    const gate = evaluateAutoGenGates(usage, now);
    if (!gate.allowed) {
      return { created: 0, reason: gate.reason, fiveHourPct: gate.fiveHourPct, weeklyPct: gate.weeklyPct };
    }

    const etfs = await getEtfsMissingReports(spaceId, batchSize);
    let created = 0;
    for (const etf of etfs) {
      // The category analyses need Morningstar data (same as the admin flow). If
      // it can't be fetched for one ETF, skip it rather than failing the batch.
      try {
        await ensureMorDataForAnalysis({ etfId: etf.id, spaceId, exchange: etf.exchange, symbol: etf.symbol });
      } catch (err) {
        console.warn(`enqueueAutoEtfGenerationBatch: skipping ${etf.symbol}:${etf.exchange} — could not ensure Mor data.`, err);
        continue;
      }
      await upsertEtfGenerationRequest({
        etfId: etf.id,
        spaceId,
        flags: ALL_ETF_SECTIONS_REGENERATE_FLAGS,
        llmProvider: LLMProvider.CLAUDE,
        llmModel: CLAUDE_AUTO_GEN.LLM_MODEL,
        autoGenerated: true,
      });
      created++;
    }

    return { created, reason: created > 0 ? 'enqueued-batch' : 'no-missing-etfs', fiveHourPct: gate.fiveHourPct, weeklyPct: gate.weeklyPct };
  } catch (err) {
    console.warn('enqueueAutoEtfGenerationBatch failed; created nothing this run.', err);
    return { created: 0, reason: 'error', fiveHourPct: null, weeklyPct: null };
  }
}
