import { prisma } from '@/prisma';
import { EtfGenerationRequestStatus } from '@/types/etf/etf-analysis-types';
import { EtfGenerationRequest } from '@prisma/client';

/**
 * The seven ETF report sections as `regenerate*` flags. Shared by the admin
 * generation-requests POST route and the nightly auto-generation job so both
 * create identical requests.
 */
export interface EtfRegenerateFlags {
  regeneratePerformanceAndReturns: boolean;
  regenerateCostEfficiencyAndTeam: boolean;
  regenerateRiskAnalysis: boolean;
  regenerateFuturePerformanceOutlook: boolean;
  regenerateKeyFacts: boolean;
  regenerateCompetition: boolean;
  regenerateFinalSummary: boolean;
}

/** All sections on — used by the nightly job's full-report requests. */
export const ALL_ETF_SECTIONS_REGENERATE_FLAGS: EtfRegenerateFlags = {
  regeneratePerformanceAndReturns: true,
  regenerateCostEfficiencyAndTeam: true,
  regenerateRiskAnalysis: true,
  regenerateFuturePerformanceOutlook: true,
  regenerateKeyFacts: true,
  regenerateCompetition: true,
  regenerateFinalSummary: true,
};

export interface UpsertEtfGenerationRequestInput {
  etfId: string;
  spaceId: string;
  flags: EtfRegenerateFlags;
  /** Provider/model override; null/undefined = use configured defaults. */
  llmProvider?: string | null;
  llmModel?: string | null;
  /** Marks the request as created by the nightly auto-generation job. */
  autoGenerated?: boolean;
}

/**
 * Creates a NotStarted ETF generation request, or updates the existing
 * NotStarted one (OR-ing in the requested sections). Mirrors the stock
 * `upsertGenerationRequest`; shared by the admin POST route and the nightly job.
 */
export async function upsertEtfGenerationRequest(input: UpsertEtfGenerationRequestInput): Promise<EtfGenerationRequest> {
  const { etfId, spaceId, flags } = input;

  const existing = await prisma.etfGenerationRequest.findFirst({
    where: { etfId, status: EtfGenerationRequestStatus.NotStarted },
    orderBy: { createdAt: 'desc' },
  });

  if (existing) {
    return prisma.etfGenerationRequest.update({
      where: { id: existing.id },
      data: {
        regeneratePerformanceAndReturns: flags.regeneratePerformanceAndReturns || existing.regeneratePerformanceAndReturns,
        regenerateCostEfficiencyAndTeam: flags.regenerateCostEfficiencyAndTeam || existing.regenerateCostEfficiencyAndTeam,
        regenerateRiskAnalysis: flags.regenerateRiskAnalysis || existing.regenerateRiskAnalysis,
        regenerateFuturePerformanceOutlook: flags.regenerateFuturePerformanceOutlook || existing.regenerateFuturePerformanceOutlook,
        regenerateKeyFacts: flags.regenerateKeyFacts || existing.regenerateKeyFacts,
        regenerateCompetition: flags.regenerateCompetition || existing.regenerateCompetition,
        regenerateFinalSummary: flags.regenerateFinalSummary || existing.regenerateFinalSummary,
        // A newly-supplied provider/model overrides the pending request; otherwise keep the existing choice.
        llmProvider: input.llmProvider ?? existing.llmProvider,
        llmModel: input.llmModel ?? existing.llmModel,
        autoGenerated: input.autoGenerated || existing.autoGenerated,
        updatedAt: new Date(),
      },
    });
  }

  return prisma.etfGenerationRequest.create({
    data: {
      etfId,
      spaceId,
      regeneratePerformanceAndReturns: flags.regeneratePerformanceAndReturns,
      regenerateCostEfficiencyAndTeam: flags.regenerateCostEfficiencyAndTeam,
      regenerateRiskAnalysis: flags.regenerateRiskAnalysis,
      regenerateFuturePerformanceOutlook: flags.regenerateFuturePerformanceOutlook,
      regenerateKeyFacts: flags.regenerateKeyFacts,
      regenerateCompetition: flags.regenerateCompetition,
      regenerateFinalSummary: flags.regenerateFinalSummary,
      llmProvider: input.llmProvider ?? null,
      llmModel: input.llmModel ?? null,
      autoGenerated: input.autoGenerated ?? false,
    },
  });
}
